### ISSUE TITLE
"SyntaxError: Unexpected reserved word" for "await"

### ISSUE THREAD

**Issue by jzohrab** [small-tech/esm-tape-runner#1]
Hello, I was trying this out on a JS project I'm hacking on, and got the below:

```
$ npx esm-tape-runner 'tests/**/*.js'
(node:73098) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/jeff/Documents/Projects/tuner/node_modules/@small-tech/esm-tape-runner/index.js:26
    await exec(`node ${test}`, { cwd: process.cwd()} )
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:88:18)
    at async link (internal/modules/esm/module_job.js:41:21)
```

Mac 10.15.7
```
MacBook-Air:tuner jeff$ node --version
v12.18.2
MacBook-Air:tuner jeff$ npx --version
6.14.5
```

Let me know if you need more detail, source code, etc.  Cheers and regards, z

**Comment by aral** [comment]
Hi there,

What version of Node are you on? From the output, it looks like it’s one where you have to use the `--experimental-modules` flag when running `node`.

Update: ah, I just saw the Node version. Hmm, I wonder if 12.x doesn’t support top-level await…

Update 2: …yep, apparently it is: https://dev.to/mikeesto/top-level-await-in-node-2jad – I don’t currently have plans of supporting versions older than the current LTS, sorry, I just don’t have the capacity to do so.

(This module is tested/supported on the latest Node.js LTS.)
